apiRules:

- exclude:
    uidRegex: '^SiaNet.Engine.BackendUtil'
    type: Class

- exclude:
    uidRegex: '^SiaNet.Engine.Layers.ActivationFunc'
    type: Class

- exclude:
    uidRegex: '^System.Object'
    type: Type